### ISSUE TITLE
Be able to use host kwarg in send method

### ISSUE THREAD

**Issue by n3storm** [tomekwojcik/envelopes#11]
I am not sure if this deserves an Issue and you can close it if you feel so, I will not complain :)

The fact is I made my report class using your excellent Envelope library (not subclassing) and I wanted to pass connection arguments as a dictionary from a class attribute. Then I see that host is not a kwarg, it feels "odd" is the only one, do you agree?

Cheers.

**Comment by tomekwojcik** [comment]
Hm, that sounds reasonable. I'll look into this, and try to modify the code so it keeps backwards compatibility.

Thanks for the issue and your interest in the project :).

**Comment by tomekwojcik** [comment]
OK, it's merged into master. Thanks for your input.

Would you mind if I added you to `AUTHORS.rst` file?
